import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
    checkForbiddenContent,
    type Finding,
    isAnchorFile,
    isBlocking,
    parseArgs,
    parseFrontmatter,
    registryPath,
    runCli,
    storeLevelFindings,
    validateAnchor,
    validatePage,
    validateRegistry,
} from "./validate-concepts";

const REPO_ROOT: string = path.resolve(__dirname, "../../..");

const DEFAULT_FRONTMATTER = `title: "Alpha"
aliases: []
touches: ["beta"]
last_updated_by: "bootstrap"
status: active
verification: verified`;

const DEFAULT_SECTIONS = `## How It Works

Alpha behaves predictably under load.

## Key Invariants

1. Alpha never breaks.

## Integration Points

- [beta](beta.md) — interacts with beta.

## Decision Log

### 2026-07-04 — #1 — Seed
Why it exists.
`;

function page(opts: { frontmatter?: string; h1?: string; lead?: string; sections?: string } = {}): string {
    const frontmatter: string = opts.frontmatter ?? DEFAULT_FRONTMATTER;
    const h1: string = opts.h1 ?? "# Alpha";
    const lead: string = opts.lead ?? "Alpha does the thing well.";
    const sections: string = opts.sections ?? DEFAULT_SECTIONS;
    return `---\n${frontmatter}\n---\n\n${h1}\n\n${lead}\n\n${sections}`;
}

const SHA_A = "a".repeat(40);
const SHA_B = "b".repeat(40);

function anchor(opts: { concept?: string; sourceSha?: string; generated?: string; marker?: boolean; bullets?: string[] } = {}): string {
    const concept = opts.concept ?? "alpha";
    const sourceSha = opts.sourceSha ?? `source_sha: ${SHA_A}`;
    const generated = opts.generated ?? "2026-07-15";
    const marker = opts.marker === false ? "" : "<!-- DERIVED — regenerated by /nxs.distill on every drain touching this concept.\n     Never hand-edit; stale anchors are rebuilt, not fixed. -->\n\n";
    const bullets = (opts.bullets ?? ["- `src/alpha.ts` — the core."]).join("\n");
    return `---\nconcept: ${concept}\n${sourceSha}\ngenerated: ${generated}\n---\n\n${marker}# Code Anchors: Alpha\n\n${bullets}\n`;
}

function validateAnchorFile(content: string, name = "alpha.md"): Finding[] {
    const dir = makeTmpDir();
    const file = writeFile(dir, path.join("anchors", name), content);
    const findings: Finding[] = [];
    validateAnchor(file, findings);
    return findings;
}

let tmpDirs: string[] = [];

function makeTmpDir(): string {
    const dir: string = fs.mkdtempSync(path.join(os.tmpdir(), "validate-concepts-"));
    tmpDirs.push(dir);
    return dir;
}

function makeGitRepo(): string {
    const dir: string = makeTmpDir();
    execFileSync("git", ["init", "-q"], { cwd: dir, stdio: "ignore" });
    execFileSync("git", ["config", "user.email", "test@example.com"], { cwd: dir, stdio: "ignore" });
    execFileSync("git", ["config", "user.name", "Test"], { cwd: dir, stdio: "ignore" });
    return dir;
}

function commitAll(dir: string, message: string): string {
    execFileSync("git", ["add", "-A"], { cwd: dir, stdio: "ignore" });
    execFileSync("git", ["commit", "-q", "-m", message], { cwd: dir, stdio: "ignore" });
    return execFileSync("git", ["rev-parse", "HEAD"], { cwd: dir, encoding: "utf8" }).trim();
}

function writeFile(dir: string, relPath: string, content: string): string {
    const file: string = path.join(dir, relPath);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    return file;
}

function validate(file: string, base: string | null = null, repoRoot: string = path.dirname(file)): Finding[] {
    const findings: Finding[] = [];
    validatePage(file, base, repoRoot, findings);
    return findings;
}

// gitShow (inside validatePage's --base branch) shells out with no explicit cwd, so it relies on
// the calling process's cwd already being inside the git repo under test — exactly how the real
// CLI behaves when invoked from anywhere inside a checkout. Mirror that here.
function validateWithCwd<T>(dir: string, fn: () => T): T {
    const original: string = process.cwd();
    process.chdir(dir);
    try {
        return fn();
    } finally {
        process.chdir(original);
    }
}

afterEach(() => {
    for (const dir of tmpDirs) {
        fs.rmSync(dir, { recursive: true, force: true });
    }
    tmpDirs = [];
});

describe("parseArgs", () => {
    it("defaults to no base, .nexus/concepts, and no files", () => {
        expect(parseArgs([])).toEqual({ base: null, conceptsDir: ".nexus/concepts", files: [] });
    });

    it("parses --base", () => {
        expect(parseArgs(["--base", "HEAD"]).base).toBe("HEAD");
    });

    it("treats a trailing --base with no value as null", () => {
        expect(parseArgs(["--base"]).base).toBeNull();
    });

    it("parses --concepts-dir", () => {
        expect(parseArgs(["--concepts-dir", "foo/bar"]).conceptsDir).toBe("foo/bar");
    });

    it("collects positional args as files and ignores a bare --", () => {
        const options = parseArgs(["--", "a.md", "b.md"]);
        expect(options.files).toEqual(["a.md", "b.md"]);
    });
});

describe("parseFrontmatter", () => {
    it("returns null when the file doesn't open with ---", () => {
        expect(parseFrontmatter(["# Title", "body"])).toBeNull();
    });

    it("returns null when the block is never terminated", () => {
        expect(parseFrontmatter(["---", "title: x", "# no closing delimiter"])).toBeNull();
    });

    it("parses an inline list field", () => {
        const fm = parseFrontmatter(['---', 'touches: ["a", "b"]', "---", ""]);
        expect(fm?.fields.get("touches")).toEqual(["a", "b"]);
    });

    it("parses a block list field", () => {
        const fm = parseFrontmatter(["---", "aliases:", "  - one", "  - two", "---", ""]);
        expect(fm?.fields.get("aliases")).toEqual(["one", "two"]);
    });

    it("strips quotes from a scalar value", () => {
        const fm = parseFrontmatter(["---", 'title: "Hello World"', "---", ""]);
        expect(fm?.fields.get("title")).toBe("Hello World");
    });
});

describe("checkForbiddenContent (§8.3)", () => {
    function check(text: string): Finding[] {
        const findings: Finding[] = [];
        checkForbiddenContent("f.md", text, findings);
        return findings;
    }

    it("flags a fenced code block", () => {
        const findings = check("```js\nconst x = 1;\n```");
        expect(findings.some((f) => f.message.includes("fenced code block"))).toBe(true);
    });

    it("flags a tilde-fenced code block", () => {
        const findings = check("~~~\ncode\n~~~");
        expect(findings.some((f) => f.message.includes("fenced code block"))).toBe(true);
    });

    it.each([
        ["a leading ./ path", "See ./scripts/build.sh for details."],
        ["a leading ../ path", "Check ../config/settings.yml."],
        ["an absolute path", "The file /etc/hosts is different."],
        ["a path with 2+ slashes", "Lives under a/b/c in the tree."],
        ["a single-slash path with a file extension", "Edit config/settings.yml directly."],
    ])("flags %s", (_label, text) => {
        const findings = check(text);
        expect(findings.some((f) => f.message.includes("file path"))).toBe(true);
    });

    it("flags call-syntax identifiers", () => {
        const findings = check("Please call foo() now.");
        expect(findings.some((f) => f.message.includes('"foo()"'))).toBe(true);
    });

    it("flags snake_case identifiers", () => {
        const findings = check("The snake_case_var holds it.");
        expect(findings.some((f) => f.message.includes("snake_case_var"))).toBe(true);
    });

    it("flags camelCase identifiers", () => {
        const findings = check("The camelCaseVar holds it.");
        expect(findings.some((f) => f.message.includes("camelCaseVar"))).toBe(true);
    });

    it("does NOT flag bare PascalCase (documented gap)", () => {
        const findings = check("FooBarType is a proper noun like GitHub.");
        expect(findings).toEqual([]);
    });
});

describe("validateAnchor", () => {
    it("passes the single-repo scalar form (regression / invariant 1)", () => {
        const findings = validateAnchorFile(anchor({ sourceSha: "source_sha: ca5265b", bullets: ["- `src/alpha.ts` — the core."] }));
        expect(findings).toEqual([]);
    });

    it("passes the hub per-repo form (AC1)", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}`,
            bullets: ["- `github.com/acme/web-app:src/app.ts` — the app."],
        }));
        expect(findings).toEqual([]);
    });

    it("passes two repos with distinct SHAs, each path attributed once (AC2)", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}\n  - github.com/acme/api@${SHA_B}`,
            bullets: [
                "- `github.com/acme/web-app:src/app.ts` — the app.",
                "- `github.com/acme/api:lib/server.ts` — the server.",
            ],
        }));
        expect(findings).toEqual([]);
    });

    it("flags a malformed list item (short SHA)", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: "source_sha:\n  - github.com/acme/web-app@abc",
            bullets: ["- `github.com/acme/web-app:src/app.ts` — the app."],
        }));
        expect(findings.some((f) => f.message.includes("source_sha[0]") && f.message.includes("40-hex"))).toBe(true);
    });

    it("flags a duplicate repo in the mapping", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}\n  - github.com/acme/web-app@${SHA_B}`,
            bullets: ["- `github.com/acme/web-app:src/app.ts` — the app."],
        }));
        expect(findings.some((f) => f.message.includes("listed more than once"))).toBe(true);
    });

    it("flags an empty source_sha list", () => {
        const findings = validateAnchorFile(anchor({ sourceSha: "source_sha:", bullets: ["- `src/alpha.ts` — the core."] }));
        expect(findings.some((f) => f.message.includes("empty"))).toBe(true);
    });

    it("flags a qualified bullet naming a repo with no source_sha entry", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}`,
            bullets: [
                "- `github.com/acme/web-app:src/app.ts` — the app.",
                "- `github.com/acme/ghost:src/x.ts` — a ghost path.",
            ],
        }));
        expect(findings.some((f) => f.message.includes("ghost") && f.message.includes("no source_sha entry"))).toBe(true);
    });

    it("flags an unqualified bullet in the per-repo form", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}`,
            bullets: ["- `src/app.ts` — the app."],
        }));
        expect(findings.some((f) => f.message.includes("not repo-qualified"))).toBe(true);
    });

    it("flags a mapped repo with zero anchored paths", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}\n  - github.com/acme/api@${SHA_B}`,
            bullets: ["- `github.com/acme/web-app:src/app.ts` — the app."],
        }));
        expect(findings.some((f) => f.message.includes("api") && f.message.includes("no anchored path"))).toBe(true);
    });

    it("flags a qualified bullet in the scalar (single-repo) form", () => {
        const findings = validateAnchorFile(anchor({
            sourceSha: "source_sha: ca5265b",
            bullets: ["- `github.com/acme/web-app:src/app.ts` — the app."],
        }));
        expect(findings.some((f) => f.message.includes("single-repo form takes unqualified paths"))).toBe(true);
    });

    it("flags a missing source_sha", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, path.join("anchors", "alpha.md"),
            "---\nconcept: alpha\ngenerated: 2026-07-15\n---\n\n<!-- DERIVED — regenerated by /nxs.distill on every drain touching this concept.\n     Never hand-edit; stale anchors are rebuilt, not fixed. -->\n\n# Code Anchors: Alpha\n\n- `src/alpha.ts` — the core.\n");
        const findings: Finding[] = [];
        validateAnchor(file, findings);
        expect(findings.some((f) => f.message.includes("missing `source_sha`"))).toBe(true);
    });

    it("flags concept not matching the filename slug", () => {
        const findings = validateAnchorFile(anchor({ concept: "beta" }));
        expect(findings.some((f) => f.message.includes("does not match"))).toBe(true);
    });

    it("flags a malformed generated date", () => {
        const findings = validateAnchorFile(anchor({ generated: "July 15" }));
        expect(findings.some((f) => f.message.includes("YYYY-MM-DD"))).toBe(true);
    });

    it("flags a missing DERIVED marker", () => {
        const findings = validateAnchorFile(anchor({ marker: false }));
        expect(findings.some((f) => f.message.includes("DERIVED"))).toBe(true);
    });

    it("flags a scalar source_sha that is not hex", () => {
        const findings = validateAnchorFile(anchor({ sourceSha: "source_sha: not-a-sha" }));
        expect(findings.some((f) => f.message.includes("hex"))).toBe(true);
    });
});

describe("anchor routing", () => {
    it("isAnchorFile is true only for files whose parent directory is 'anchors'", () => {
        expect(isAnchorFile("/x/.nexus/anchors/alpha.md")).toBe(true);
        expect(isAnchorFile("/x/.nexus/concepts/alpha.md")).toBe(false);
    });

    it("runCli routes an anchors/ file to anchor validation, not page validation", () => {
        const dir = makeTmpDir();
        writeFile(dir, path.join("anchors", "alpha.md"), anchor({
            sourceSha: `source_sha:\n  - github.com/acme/web-app@${SHA_A}`,
            bullets: ["- `src/app.ts` — the app."], // unqualified — invalid in per-repo form
        }));
        const errors: string[] = [];
        const originalError = console.error;
        console.error = (msg: string) => errors.push(msg);
        let status: number;
        try {
            status = runCli([path.join(dir, "anchors", "alpha.md")]);
        } finally {
            console.error = originalError;
        }
        expect(status).toBe(1);
        expect(errors.some((line) => line.includes("not repo-qualified"))).toBe(true);
        expect(errors.some((line) => line.includes("missing `title`"))).toBe(false);
    });

    it("runCli exits 0 for a valid anchor file", () => {
        const dir = makeTmpDir();
        writeFile(dir, path.join("anchors", "alpha.md"), anchor());
        const status = runCli([path.join(dir, "anchors", "alpha.md")]);
        expect(status).toBe(0);
    });

    it("the default no-files scan still reads only the concepts dir (unchanged)", () => {
        const dir = makeTmpDir();
        writeFile(dir, "alpha.md", page());
        expect(runCli(["--concepts-dir", dir])).toBe(0);
    });
});

describe("validatePage", () => {
    it("reports no findings for a well-formed page", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page());
        expect(validate(file)).toEqual([]);
    });

    it("flags a non-kebab-case slug", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "Alpha_Bad.md", page());
        expect(validate(file).some((f) => f.message.includes("is not kebab-case"))).toBe(true);
    });

    it("flags missing/unterminated frontmatter and stops there", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", "# Alpha\n\nNo frontmatter here.\n");
        const findings = validate(file);
        expect(findings).toHaveLength(1);
        expect(findings[0].message).toContain("missing or unterminated frontmatter block");
    });

    it("flags a missing title", () => {
        const dir = makeTmpDir();
        const fm = `aliases: []
touches: ["beta"]
last_updated_by: "bootstrap"
status: active
verification: verified`;
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes("missing `title`"))).toBe(true);
    });

    it.each(["aliases", "touches"])("flags a missing list field `%s`", (field) => {
        const dir = makeTmpDir();
        const lines = DEFAULT_FRONTMATTER.split("\n").filter((line) => !line.startsWith(`${field}:`));
        const file = writeFile(dir, "alpha.md", page({ frontmatter: lines.join("\n") }));
        expect(validate(file).some((f) => f.message.includes(`missing list field \`${field}\``))).toBe(true);
    });

    it("flags a bad last_updated_by", () => {
        const dir = makeTmpDir();
        const fm = DEFAULT_FRONTMATTER.replace('last_updated_by: "bootstrap"', 'last_updated_by: "randomguy"');
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes("`last_updated_by` must be"))).toBe(true);
    });

    it("flags a bad status", () => {
        const dir = makeTmpDir();
        const fm = DEFAULT_FRONTMATTER.replace("status: active", "status: wip");
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes("`status` must be"))).toBe(true);
    });

    it("flags a bad verification value", () => {
        const dir = makeTmpDir();
        const fm = DEFAULT_FRONTMATTER.replace("verification: verified", "verification: maybe");
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes("`verification` must be"))).toBe(true);
    });

    it.each(["slug", "id"])("flags a derived `%s` field in frontmatter", (field) => {
        const dir = makeTmpDir();
        const fm = `${DEFAULT_FRONTMATTER}\n${field}: alpha`;
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes(`\`${field}\` is derived state`))).toBe(true);
    });

    it("flags a missing H1", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ h1: "" }));
        expect(validate(file).some((f) => f.message.includes("missing H1"))).toBe(true);
    });

    it("flags an H1 that doesn't mirror the title", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ h1: "# Beta" }));
        expect(validate(file).some((f) => f.message.includes("does not mirror title"))).toBe(true);
    });

    it("flags a missing Summary lead", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ lead: "" }));
        expect(validate(file).some((f) => f.message.includes("no Summary lead"))).toBe(true);
    });

    it.each(["How It Works", "Key Invariants", "Integration Points", "Decision Log"])(
        "flags a missing required section `## %s`",
        (heading) => {
            const dir = makeTmpDir();
            const sections = DEFAULT_SECTIONS
                .split("\n\n")
                .filter((block) => !block.startsWith(`## ${heading}`))
                .join("\n\n");
            const file = writeFile(dir, "alpha.md", page({ sections }));
            expect(validate(file).some((f) => f.message.includes(`missing required section \`## ${heading}\``))).toBe(true);
        }
    );

    it("flags a body exceeding the 400-word cap", () => {
        const dir = makeTmpDir();
        const filler = "filler ".repeat(450).trim();
        const sections = `## How It Works

${filler}

## Key Invariants

1. Alpha never breaks.

## Integration Points

- [beta](beta.md) — interacts with beta.

## Decision Log

### 2026-07-04 — #1 — Seed
Why it exists.
`;
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("exceeds the 400-word cap"))).toBe(true);
    });

    it("flags more than 7 numbered invariants", () => {
        const dir = makeTmpDir();
        const invariants = Array.from({ length: 8 }, (_, i) => `${i + 1}. Invariant ${i + 1}.`).join("\n");
        const sections = `## How It Works

Alpha behaves predictably under load.

## Key Invariants

${invariants}

## Integration Points

- [beta](beta.md) — interacts with beta.

## Decision Log

### 2026-07-04 — #1 — Seed
Why it exists.
`;
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("exceeds the cap of 7"))).toBe(true);
    });

    it("flags a touches entry with no matching Integration Points bullet", () => {
        const dir = makeTmpDir();
        const fm = DEFAULT_FRONTMATTER.replace('touches: ["beta"]', 'touches: ["beta", "gamma"]');
        const file = writeFile(dir, "alpha.md", page({ frontmatter: fm }));
        expect(validate(file).some((f) => f.message.includes('touches: "gamma" has no Integration Points bullet'))).toBe(true);
    });

    it("flags an Integration Points bullet missing from touches", () => {
        const dir = makeTmpDir();
        const sections = DEFAULT_SECTIONS.replace(
            "- [beta](beta.md) — interacts with beta.",
            "- [beta](beta.md) — interacts with beta.\n- [gamma](gamma.md) — interacts with gamma."
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes('Integration Points names "gamma" missing from touches'))).toBe(true);
    });

    it("flags a link label/target mismatch in Integration Points", () => {
        const dir = makeTmpDir();
        const sections = DEFAULT_SECTIONS.replace(
            "- [beta](beta.md) — interacts with beta.",
            "- [beta](gamma.md) — interacts with beta."
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("disagree"))).toBe(true);
    });

    it("flags an Integration Points bullet not shaped as a [slug](slug.md) link", () => {
        const dir = makeTmpDir();
        const sections = DEFAULT_SECTIONS.replace(
            "- [beta](beta.md) — interacts with beta.",
            "- beta, without a link"
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("does not lead with a [slug](slug.md) link"))).toBe(true);
    });

    it("flags an empty Decision Log section", () => {
        const dir = makeTmpDir();
        const sections = `## How It Works

Alpha behaves predictably under load.

## Key Invariants

1. Alpha never breaks.

## Integration Points

- [beta](beta.md) — interacts with beta.

## Decision Log
`;
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("Decision Log: empty"))).toBe(true);
    });

    it("flags a malformed Decision Log heading", () => {
        const dir = makeTmpDir();
        const sections = DEFAULT_SECTIONS.replace(
            "### 2026-07-04 — #1 — Seed",
            "### not a valid heading"
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("malformed heading"))).toBe(true);
    });

    it("flags a bad provenance ref in a Decision Log heading", () => {
        const dir = makeTmpDir();
        const sections = DEFAULT_SECTIONS.replace(
            "### 2026-07-04 — #1 — Seed",
            "### 2026-07-04 — randomguy — Seed"
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("bad provenance ref"))).toBe(true);
    });

    it("flags an H3 heading found outside the Decision Log", () => {
        const dir = makeTmpDir();
        const sections = `## How It Works

Alpha behaves predictably under load.

### Stray Heading

More prose.

## Key Invariants

1. Alpha never breaks.

## Integration Points

- [beta](beta.md) — interacts with beta.

## Decision Log

### 2026-07-04 — #1 — Seed
Why it exists.
`;
        const file = writeFile(dir, "alpha.md", page({ sections }));
        expect(validate(file).some((f) => f.message.includes("H3 headings found outside the Decision Log"))).toBe(true);
    });
});

// ---------------------------------------------------------------------------------------------
// Epic #220 — the cap measures a page's own content, never its neighbour list.
// ---------------------------------------------------------------------------------------------

/** A page with `ownWords` words of own content and one Integration Points bullet per entry. */
function pageWithOwnContent(ownWords: number, bullets: string[] = ["- [beta](beta.md) — interacts with beta."]): string {
    const slugs: string[] = bullets
        .map((b) => b.match(/\[([a-z0-9-]+)\]/)?.[1] ?? "")
        .filter((s) => s !== "");
    const frontmatter: string = DEFAULT_FRONTMATTER.replace(
        'touches: ["beta"]',
        `touches: [${slugs.map((s) => `"${s}"`).join(", ")}]`
    );
    // The lead ("Alpha does the thing well.") is own content too: 5 words.
    const filler: string = "filler ".repeat(Math.max(0, ownWords - 5 - 4 - 3)).trim();
    const sections = `## How It Works

${filler}

## Key Invariants

1. Alpha never breaks.

## Integration Points

${bullets.join("\n")}

## Decision Log

### 2026-07-04 — #1 — Seed
Why it exists.
`;
    return page({ frontmatter, sections });
}

function capFindings(file: string): Finding[] {
    return validate(file).filter((f) => f.message.includes("cap — split the concept"));
}

describe("the body cap counts a page's own content (#222)", () => {
    it("flags a page whose own content exceeds the cap", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(450));
        expect(capFindings(file)).toHaveLength(1);
        expect(capFindings(file)[0].message).toContain("own content");
    });

    it("does not flag a page whose total body passes 400 words only through Integration Points", () => {
        const dir = makeTmpDir();
        const bullets: string[] = Array.from(
            { length: 20 },
            (_, i) => `- [n${i}](n${i}.md) — ${"neighbour ".repeat(12).trim()}.`
        );
        const content: string = pageWithOwnContent(380, bullets);
        const bodyWords: number = content.split("\n").slice(11).join(" ").split(/\s+/).filter((w) => w !== "").length;
        expect(bodyWords).toBeGreaterThan(400);

        const file = writeFile(dir, "alpha.md", content);
        expect(capFindings(file)).toEqual([]);
    });

    it("keeps the Decision Log excluded from the counted region exactly as before", () => {
        const dir = makeTmpDir();
        const log: string = "history ".repeat(500).trim();
        const content: string = pageWithOwnContent(380).replace("Why it exists.", log);
        const file = writeFile(dir, "alpha.md", content);
        expect(capFindings(file)).toEqual([]);
    });

    it("counts a section a page invents, so the cap cannot be evaded by adding a heading", () => {
        const dir = makeTmpDir();
        const content: string = pageWithOwnContent(200).replace(
            "## Integration Points",
            `## Appendix\n\n${"extra ".repeat(300).trim()}\n\n## Integration Points`
        );
        const file = writeFile(dir, "alpha.md", content);
        expect(capFindings(file)).toHaveLength(1);
    });

    it("reports no body-cap finding on any active page in the store, unedited", () => {
        const conceptsDir: string = path.join(REPO_ROOT, ".nexus", "concepts");
        const pages: string[] = fs.readdirSync(conceptsDir).filter((n) => n.endsWith(".md") && n !== "README.md");
        expect(pages.length).toBeGreaterThan(0);

        const findings: Finding[] = [];
        for (const name of pages) {
            validatePage(path.join(conceptsDir, name), null, REPO_ROOT, findings);
        }
        expect(findings.filter((f) => f.message.includes("cap — split the concept"))).toEqual([]);
    });
});

describe("the neighbour list is bounded per entry (#223)", () => {
    function bulletOf(slug: string, words: number): string {
        return `- [${slug}](${slug}.md) — ${"word ".repeat(Math.max(0, words - 3)).trim()}.`;
    }

    it("flags a bullet over the 40-word ceiling and fails the run", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, [bulletOf("beta", 41)]));
        const blocking: Finding[] = validate(file).filter((f) => f.severity !== "advisory");
        expect(blocking.some((f) => f.message.includes("40-word ceiling"))).toBe(true);
    });

    it("accepts a bullet exactly at the ceiling — the ceiling blocks on a strict greater-than", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, [bulletOf("beta", 40)]));
        expect(validate(file).some((f) => f.message.includes("40-word ceiling"))).toBe(false);
    });

    it("measures a bullet across its wrapped continuation lines", () => {
        const dir = makeTmpDir();
        const wrapped = `- [beta](beta.md) — ${"word ".repeat(20).trim()}\n  ${"word ".repeat(21).trim()}.`;
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, [wrapped]));
        expect(validate(file).some((f) => f.message.includes("40-word ceiling"))).toBe(true);
    });

    it("reports a bullet over the 25-word advisory without failing the run", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, [bulletOf("beta", 30)]));
        const findings: Finding[] = validate(file);
        const advisory: Finding | undefined = findings.find((f) => f.message.includes("25-word advisory"));
        expect(advisory?.severity).toBe("advisory");
        expect(findings.filter((f) => f.severity !== "advisory")).toEqual([]);
    });

    it("names a page over 12 bullets in a high-degree advisory without failing the run", () => {
        const dir = makeTmpDir();
        const bullets: string[] = Array.from({ length: 13 }, (_, i) => bulletOf(`n${i}`, 8));
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, bullets));
        const findings: Finding[] = validate(file);
        const advisory: Finding | undefined = findings.find((f) => f.message.includes("high-degree"));
        expect(advisory?.severity).toBe("advisory");
        expect(advisory?.message).toContain("13");
        expect(findings.filter((f) => f.severity !== "advisory")).toEqual([]);
    });

    it("leaves a page at the degree threshold unremarked", () => {
        const dir = makeTmpDir();
        const bullets: string[] = Array.from({ length: 12 }, (_, i) => bulletOf(`n${i}`, 8));
        const file = writeFile(dir, "alpha.md", pageWithOwnContent(100, bullets));
        expect(validate(file).some((f) => f.message.includes("high-degree"))).toBe(false);
    });

    it("keeps every Integration Points bullet in the store under the ceiling, and names the store's hub", () => {
        const conceptsDir: string = path.join(REPO_ROOT, ".nexus", "concepts");
        const pages: string[] = fs.readdirSync(conceptsDir).filter((n) => n.endsWith(".md") && n !== "README.md");
        const findings: Finding[] = [];
        for (const name of pages) {
            validatePage(path.join(conceptsDir, name), null, REPO_ROOT, findings);
        }
        expect(findings.filter((f) => f.severity !== "advisory")).toEqual([]);

        const hub: Finding | undefined = findings.find((f) => f.message.includes("high-degree"));
        expect(hub?.file).toContain("distiller.md");
    });
});

describe("store-level revisit trigger (#223)", () => {
    it("reports neither trigger on the store as it stands", () => {
        const conceptsDir: string = path.join(REPO_ROOT, ".nexus", "concepts");
        const findings: Finding[] = storeLevelFindings(conceptsDir);
        expect(findings).toEqual([]);
    });

    it("advises when neighbour prose passes a quarter of all body text", () => {
        const dir = makeTmpDir();
        const bullets: string[] = Array.from({ length: 8 }, (_, i) => `- [n${i}](n${i}.md) — ${"neighbour ".repeat(20).trim()}.`);
        writeFile(dir, "alpha.md", pageWithOwnContent(100, bullets));
        const findings: Finding[] = storeLevelFindings(dir);
        expect(findings.some((f) => f.message.includes("25% revisit trigger"))).toBe(true);
        expect(findings.every((f) => f.severity === "advisory")).toBe(true);
    });

    it("advises when the highest-degree page passes 25 bullets", () => {
        const dir = makeTmpDir();
        const bullets: string[] = Array.from({ length: 26 }, (_, i) => `- [n${i}](n${i}.md) — brief.`);
        writeFile(dir, "alpha.md", pageWithOwnContent(340, bullets));
        const findings: Finding[] = storeLevelFindings(dir);
        const trigger: Finding | undefined = findings.find((f) => f.message.includes("25-bullet revisit trigger"));
        expect(trigger?.severity).toBe("advisory");
        expect(trigger?.message).toContain("alpha");
    });
});

describe("severity and exit status (#223)", () => {
    function runInDir(dir: string): { code: number; out: string; err: string } {
        const out: string[] = [];
        const err: string[] = [];
        const log = console.log;
        const error = console.error;
        console.log = (m: string) => void out.push(m);
        console.error = (m: string) => void err.push(m);
        try {
            const code: number = validateWithCwd(dir, () => runCli(["--concepts-dir", "concepts"]));
            return { code, out: out.join("\n"), err: err.join("\n") };
        } finally {
            console.log = log;
            console.error = error;
        }
    }

    it("exits zero when the only findings are advisories, and marks them as such", () => {
        const dir = makeTmpDir();
        writeFile(dir, "concepts/alpha.md", pageWithOwnContent(100, [`- [beta](beta.md) — ${"word ".repeat(30).trim()}.`]));
        const result = runInDir(dir);
        expect(result.code).toBe(0);
        expect(result.err).toContain("ADVISORY");
        expect(result.err).not.toContain("BLOCKING");
    });

    it("exits non-zero and distinguishes the two classes when a blocking finding is present", () => {
        const dir = makeTmpDir();
        writeFile(dir, "concepts/alpha.md", pageWithOwnContent(100, [`- [beta](beta.md) — ${"word ".repeat(41).trim()}.`]));
        const result = runInDir(dir);
        expect(result.code).toBe(1);
        expect(result.err).toContain("BLOCKING");
        expect(result.err).toMatch(/1 blocking finding\(s\)/);
    });
});

// A drain must always be able to declare a real interaction (#224): the reciprocity fan-out writes
// one bullet onto the neighbour, and no page in the store may reject it for cap reasons.
describe("a reciprocal bullet is always writable (#224)", () => {
    const NEW_EDGE = "- [new-neighbour](new-neighbour.md) — the neighbour this drain declares, named here so the interaction is an edge rather than prose.";

    function withReciprocalBullet(slug: string): Finding[] {
        const dir = makeTmpDir();
        const source: string = fs.readFileSync(path.join(REPO_ROOT, ".nexus", "concepts", `${slug}.md`), "utf8");
        const lines: string[] = source.split("\n");
        const touchesLine: number = lines.findIndex((l) => l.startsWith("touches:"));
        lines[touchesLine] = lines[touchesLine].replace(/\]\s*$/, ', "new-neighbour"]');
        const ipStart: number = lines.findIndex((l) => l.trim() === "## Integration Points");
        const nextSection: number = lines.findIndex((l, i) => i > ipStart && /^## /.test(l));
        lines.splice(nextSection - 1, 0, NEW_EDGE);

        const file = writeFile(dir, `${slug}.md`, lines.join("\n"));
        const findings: Finding[] = [];
        validatePage(file, null, dir, findings);
        return findings;
    }

    it.each([
        "distiller", // the store's highest-degree page
        // The three pages the #219 drain could not link into, and recorded as prose instead.
        "publishing-config-resolution",
        "issue-sourced-planning",
        "durable-close-record",
    ])("accepts a new edge on %s with no split and no eviction", (slug) => {
        expect(withReciprocalBullet(slug).filter(isBlocking)).toEqual([]);
    });
});

describe("validatePage — --base append-only mode", () => {
    it("treats a base version with no Decision Log section as having zero prior entries", () => {
        const dir = makeGitRepo();
        const noLogSections = `## How It Works

Alpha behaves predictably under load.

## Key Invariants

1. Alpha never breaks.

## Integration Points

- [beta](beta.md) — interacts with beta.
`;
        const file = writeFile(dir, "alpha.md", page({ sections: noLogSections }));
        const sha = commitAll(dir, "seed");
        fs.writeFileSync(file, page());
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.filter((f) => f.message.includes("Decision Log"))).toEqual([]);
    });

    it("enforces nothing when the page is unchanged against base", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page());
        const sha = commitAll(dir, "seed");
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings).toEqual([]);
    });

    it("passes when a changed page gains exactly one new Decision Log entry", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page());
        const sha = commitAll(dir, "seed");
        const sections = DEFAULT_SECTIONS.replace(
            "Why it exists.\n",
            `Why it exists.

### 2026-07-05 — #2 — Follow-up
More context.
`
        );
        fs.writeFileSync(file, page({ sections }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.filter((f) => f.message.includes("Decision Log"))).toEqual([]);
    });

    it("flags a changed page that gained zero new Decision Log entries", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page());
        const sha = commitAll(dir, "seed");
        fs.writeFileSync(file, page({ lead: "Alpha does the thing well, updated." }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("gained 0 entries"))).toBe(true);
    });

    it("flags a changed page that gained two new Decision Log entries", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page());
        const sha = commitAll(dir, "seed");
        const sections = DEFAULT_SECTIONS.replace(
            "Why it exists.\n",
            `Why it exists.

### 2026-07-05 — #2 — Follow-up
More.

### 2026-07-06 — #3 — Another
Even more.
`
        );
        fs.writeFileSync(file, page({ sections }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("gained 2 entries"))).toBe(true);
    });

    it("flags an edited prior Decision Log entry even when exactly one entry was added", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page());
        const sha = commitAll(dir, "seed");
        const sections = DEFAULT_SECTIONS
            .replace("### 2026-07-04 — #1 — Seed", "### 2026-07-05 — #1 — Seed")
            .replace(
                "Why it exists.\n",
                `Why it exists.

### 2026-07-06 — #2 — Follow-up
More.
`
            );
        fs.writeFileSync(file, page({ sections }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("append-only"))).toBe(true);
    });

    it("requires exactly one entry on a brand-new page not present at base", () => {
        const dir = makeGitRepo();
        writeFile(dir, "placeholder.md", page({ h1: "# Placeholder", frontmatter: DEFAULT_FRONTMATTER.replace("Alpha", "Placeholder") }));
        const sha = commitAll(dir, "seed");
        const file = writeFile(dir, "alpha.md", page());
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.filter((f) => f.message.includes("Decision Log"))).toEqual([]);
    });

    it("flags a brand-new page that doesn't carry exactly one entry", () => {
        const dir = makeGitRepo();
        writeFile(dir, "placeholder.md", page({ h1: "# Placeholder", frontmatter: DEFAULT_FRONTMATTER.replace("Alpha", "Placeholder") }));
        const sha = commitAll(dir, "seed");
        const sections = DEFAULT_SECTIONS.replace(
            "Why it exists.\n",
            `Why it exists.

### 2026-07-05 — #2 — Follow-up
More.
`
        );
        const file = writeFile(dir, "alpha.md", page({ sections }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("new page must carry exactly one entry"))).toBe(true);
    });

    it("finds the pre-archive content via the _archive fallback path", () => {
        const dir = makeGitRepo();
        const original = writeFile(dir, "concepts/alpha.md", page());
        const sha = commitAll(dir, "seed");
        fs.rmSync(original);
        const sections = DEFAULT_SECTIONS.replace(
            "Why it exists.\n",
            `Why it exists.

### 2026-07-05 — #2 — Archived
No longer active.
`
        );
        const archived = writeFile(dir, "concepts/_archive/alpha.md", page({ sections }));
        const findings = validateWithCwd(dir, () => validate(archived, sha, dir));
        // Gained exactly one entry relative to the pre-archive content found via the fallback —
        // if the fallback didn't work, `previous` would be null and this would instead fail as
        // "new page must carry exactly one entry (found 2)".
        expect(findings.filter((f) => f.message.includes("Decision Log"))).toEqual([]);
    });
});

describe("runCli", () => {
    it("returns 0 and reports the concept directory as absent when it doesn't exist", () => {
        const dir = makeTmpDir();
        const logs: string[] = [];
        const originalLog = console.log;
        console.log = (msg: string) => logs.push(msg);
        try {
            const status = runCli(["--concepts-dir", path.join(dir, "missing")]);
            expect(status).toBe(0);
            expect(logs.some((line) => line.includes("nothing to validate"))).toBe(true);
        } finally {
            console.log = originalLog;
        }
    });

    it("returns 1 when a listed file does not exist", () => {
        const dir = makeTmpDir();
        const status = runCli(["--concepts-dir", dir, path.join(dir, "missing.md")]);
        expect(status).toBe(1);
    });

    it("returns 0 for a clean concepts directory", () => {
        const dir = makeTmpDir();
        writeFile(dir, "alpha.md", page());
        expect(runCli(["--concepts-dir", dir])).toBe(0);
    });

    it("returns 1 when a page has findings", () => {
        const dir = makeTmpDir();
        writeFile(dir, "alpha.md", page({ h1: "# Mismatched Title" }));
        expect(runCli(["--concepts-dir", dir])).toBe(1);
    });
});

// --- domain registry (epic #89, STORY-89.01) --------------------------------
// Fixture strings duplicated from domain-registry.spec.ts (no shared fixtures module — CLAUDE.md
// forbids barrel-style re-export files).

const REGISTRY_WELL_FORMED =
`# Domain Registry

## Connectors
\`connectors\`

Everything about pulling data in from and pushing it out to external systems.

### Catalog
\`catalog\`

The registry of available connector types and their published metadata.

### Runtime
\`runtime\`

How a configured connector executes when a flow runs.

## Sources
\`sources\`

Upstream systems and the shape of the data they provide.

### Catalog
\`catalog\`

The inventory of known source systems.
`;

const REGISTRY_THIRD_LEVEL =
`## Connectors
\`connectors\`

Rubric for connectors.

### Catalog
\`catalog\`

Rubric for catalog.

#### Nested Too Deep
\`nested\`

This nests a third level and must be rejected.
`;

const REGISTRY_DUP_PATH =
`## Connectors
\`connectors\`

First connectors rubric.

## Connectors Again
\`connectors\`

A second entry claiming the same slug path.
`;

const REGISTRY_MISSING_TITLE =            // note the trailing space after "##"
`## 
\`connectors\`

Rubric with no domain title.
`;

const REGISTRY_MISSING_SLUG =
`## Connectors

Everything about connectors, but the slug line is missing entirely.
`;

const REGISTRY_MISSING_RUBRIC =
`## Connectors
\`connectors\`

## Sources
\`sources\`

Sources rubric present so only the first entry lacks a rubric.
`;

// --- domain filing (epic #89, STORY-89.02) ----------------------------------

const VALID_DOMAIN_PATHS = new Set(["connectors", "connectors/catalog", "connectors/runtime", "sources", "sources/catalog"]);

function validateDom(file: string, validPaths: Set<string> | null): Finding[] {
    const findings: Finding[] = [];
    validatePage(file, null, path.dirname(file), findings, validPaths);
    return findings;
}

const FM_WITH_DOMAIN = `${DEFAULT_FRONTMATTER}\ndomain: connectors`;
const FM_WITH_DOMAIN_SOURCES = `${DEFAULT_FRONTMATTER}\ndomain: sources`;

describe("validatePage — domain filing (STORY-89.02)", () => {
    it("AC(a) resolves at a domain → pass", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const findings = validateDom(file, VALID_DOMAIN_PATHS);
        expect(findings.some((f) => f.message.includes("domain"))).toBe(false);
    });

    it("AC(a) resolves at a subdomain → pass", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: `${DEFAULT_FRONTMATTER}\ndomain: connectors/catalog` }));
        const findings = validateDom(file, VALID_DOMAIN_PATHS);
        expect(findings.some((f) => f.message.includes("domain"))).toBe(false);
    });

    it("AC(b) parent filing with subdomains present → pass", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const findings = validateDom(file, VALID_DOMAIN_PATHS);
        expect(findings.some((f) => f.message.includes("domain"))).toBe(false);
    });

    it("AC(a) undefined path → fail naming the page", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: `${DEFAULT_FRONTMATTER}\ndomain: nope/not-real` }));
        const findings = validateDom(file, VALID_DOMAIN_PATHS);
        const finding = findings.find((f) => f.message.includes("does not resolve"));
        expect(finding?.file).toBe(file);
        expect(finding?.message).toContain("nope/not-real");
    });

    it("AC(a) absent field with registry present → fail naming the page", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page());
        const findings = validateDom(file, VALID_DOMAIN_PATHS);
        const finding = findings.find((f) => f.message.includes("missing") && f.message.includes("domain"));
        expect(finding?.file).toBe(file);
    });

    it("AC(c) no registry → no domain finding even when absent", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "alpha.md", page());
        const findings = validateDom(file, null);
        expect(findings.some((f) => f.message.includes("domain"))).toBe(false);
    });

    it("leaf reuse resolves under either parent", () => {
        const dir = makeTmpDir();
        const sourcesFile = writeFile(dir, "alpha.md", page({ frontmatter: `${DEFAULT_FRONTMATTER}\ndomain: sources/catalog` }));
        expect(validateDom(sourcesFile, VALID_DOMAIN_PATHS).some((f) => f.message.includes("domain"))).toBe(false);
        const connectorsFile = writeFile(dir, "beta.md", page({ frontmatter: `${DEFAULT_FRONTMATTER}\ndomain: connectors/catalog` }));
        expect(validateDom(connectorsFile, VALID_DOMAIN_PATHS).some((f) => f.message.includes("domain"))).toBe(false);
    });
});

describe("runCli — domain filing (STORY-89.02)", () => {
    let originalCwd: string;

    afterEach(() => {
        if (originalCwd) {
            process.chdir(originalCwd);
        }
    });

    function chdirTmp(): string {
        originalCwd = process.cwd();
        const dir = makeTmpDir();
        process.chdir(dir);
        return dir;
    }

    it("AC(a) end-to-end pass", () => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), REGISTRY_WELL_FORMED);
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page({ frontmatter: FM_WITH_DOMAIN }));
        expect(runCli([])).toBe(0);
    });

    it("AC(a) undefined path → exit 1, names the page", () => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), REGISTRY_WELL_FORMED);
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page({ frontmatter: `${DEFAULT_FRONTMATTER}\ndomain: ghosts` }));
        const errors: string[] = [];
        const originalError = console.error;
        console.error = (msg: string) => errors.push(msg);
        let status: number;
        try {
            status = runCli([]);
        } finally {
            console.error = originalError;
        }
        expect(status).toBe(1);
        expect(errors.some((line) => line.includes("alpha.md") && line.includes("does not resolve"))).toBe(true);
    });

    it("AC(a) absent field → exit 1, names the page", () => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), REGISTRY_WELL_FORMED);
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page());
        const errors: string[] = [];
        const originalError = console.error;
        console.error = (msg: string) => errors.push(msg);
        let status: number;
        try {
            status = runCli([]);
        } finally {
            console.error = originalError;
        }
        expect(status).toBe(1);
        expect(errors.some((line) => line.includes("alpha.md") && line.includes("missing") && line.includes("domain"))).toBe(true);
    });

    it("AC(b) parent filing → exit 0", () => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), REGISTRY_WELL_FORMED);
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page({ frontmatter: FM_WITH_DOMAIN }));
        expect(runCli([])).toBe(0);
    });

    it("AC(c) no-registry no-op", () => {
        chdirTmp();
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page());
        const errors: string[] = [];
        const originalError = console.error;
        console.error = (msg: string) => errors.push(msg);
        let status: number;
        try {
            status = runCli([]);
        } finally {
            console.error = originalError;
        }
        expect(status).toBe(0);
        expect(errors.some((line) => line.includes("domain"))).toBe(false);
    });
});

describe("validatePage — Decision Log domain-only exemption (STORY-89.02)", () => {
    it("AC(d) domain-only change → exempt, passes", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const sha = commitAll(dir, "seed");
        fs.writeFileSync(file, page({ frontmatter: FM_WITH_DOMAIN_SOURCES }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("Decision Log"))).toBe(false);
    });

    it("AC(d) domain-plus-body change → not exempt, must carry an entry", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const sha = commitAll(dir, "seed");
        fs.writeFileSync(file, page({ frontmatter: FM_WITH_DOMAIN_SOURCES, lead: "Alpha does the thing well, revised." }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("gained 0 entries"))).toBe(true);
    });

    it("AC(d) body-only change → unchanged behavior", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const sha = commitAll(dir, "seed");
        fs.writeFileSync(file, page({ frontmatter: FM_WITH_DOMAIN, lead: "Alpha does the thing well, revised." }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("gained 0 entries"))).toBe(true);
    });

    it("AC(d) append-only still holds under a domain-only change", () => {
        const dir = makeGitRepo();
        const file = writeFile(dir, "alpha.md", page({ frontmatter: FM_WITH_DOMAIN }));
        const sha = commitAll(dir, "seed");
        const sections = DEFAULT_SECTIONS.replace("### 2026-07-04 — #1 — Seed", "### 2026-07-05 — #1 — Seed");
        fs.writeFileSync(file, page({ frontmatter: FM_WITH_DOMAIN_SOURCES, sections }));
        const findings = validateWithCwd(dir, () => validate(file, sha, dir));
        expect(findings.some((f) => f.message.includes("append-only"))).toBe(true);
    });
});

describe("domain registry (epic #89, STORY-89.01)", () => {
    let originalCwd: string;

    afterEach(() => {
        if (originalCwd) {
            process.chdir(originalCwd);
        }
    });

    function chdirTmp(): string {
        originalCwd = process.cwd();
        const dir = makeTmpDir();
        process.chdir(dir);
        return dir;
    }

    it("registryPath resolves beside the atlas in single-repo mode", () => {
        const dir = makeTmpDir();
        const result = registryPath(dir);
        expect(result.endsWith("domains.md")).toBe(true);
        expect(result).toBe(path.join("docs", "domains.md"));
    });

    it("validateRegistry maps parser findings onto the registry file", () => {
        const dir = makeTmpDir();
        const file = writeFile(dir, "domains.md", REGISTRY_THIRD_LEVEL);
        const findings: Finding[] = [];
        validateRegistry(file, findings);
        expect(findings.length).toBeGreaterThan(0);
        for (const finding of findings) {
            expect(finding.file).toBe(file);
        }
    });

    it.each([
        ["WELL_FORMED", REGISTRY_WELL_FORMED, 0],
        ["THIRD_LEVEL", REGISTRY_THIRD_LEVEL, 1],
        ["DUP_PATH", REGISTRY_DUP_PATH, 1],
        ["MISSING_TITLE", REGISTRY_MISSING_TITLE, 1],
        ["MISSING_SLUG", REGISTRY_MISSING_SLUG, 1],
        ["MISSING_RUBRIC", REGISTRY_MISSING_RUBRIC, 1],
    ])("AC4 — %s registry exits with code %i", (_label, fixture, expectedStatus) => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), fixture);
        const status = runCli([]);
        expect(status).toBe(expectedStatus);
    });

    it("no-registry no-op: a store with no registry raises zero domain findings (Invariant 5)", () => {
        chdirTmp();
        fs.mkdirSync(".nexus/concepts", { recursive: true });
        fs.writeFileSync(path.join(".nexus", "concepts", "alpha.md"), page());
        const errors: string[] = [];
        const originalError = console.error;
        console.error = (msg: string) => errors.push(msg);
        let status: number;
        try {
            status = runCli([]);
        } finally {
            console.error = originalError;
        }
        expect(status).toBe(0);
        expect(errors.some((line) => line.includes("slug path") || line.includes("domains.md"))).toBe(false);
    });

    it("the registry is never validated as a concept page (Invariant 6)", () => {
        chdirTmp();
        fs.mkdirSync("docs", { recursive: true });
        fs.writeFileSync(path.join("docs", "domains.md"), REGISTRY_WELL_FORMED);
        const status = runCli(["docs/domains.md"]);
        expect(status).toBe(0);
    });
});

describe("CLI (subprocess)", () => {
    function runViaTsx(args: string[]): { status: number; stdout: string; stderr: string } {
        try {
            const stdout: string = execFileSync("npx", ["tsx", "libs/portable-tools/src/validate-concepts-launcher.ts", ...args], {
                cwd: REPO_ROOT,
                encoding: "utf8",
            });
            return { status: 0, stdout, stderr: "" };
        } catch (error) {
            const err = error as { status: number; stdout: string; stderr: string };
            return { status: err.status, stdout: err.stdout, stderr: err.stderr };
        }
    }

    it("exits 0 and prints the validated count for a clean directory", () => {
        const dir = makeTmpDir();
        writeFile(dir, "alpha.md", page());
        const result = runViaTsx(["--concepts-dir", dir]);
        expect(result.status).toBe(0);
        expect(result.stdout).toContain("OK: 1 page(s) validated.");
    });

    it("exits 1 and prints the finding count for a directory with findings", () => {
        const dir = makeTmpDir();
        writeFile(dir, "alpha.md", page({ h1: "# Mismatched Title" }));
        const result = runViaTsx(["--concepts-dir", dir]);
        expect(result.status).toBe(1);
        expect(result.stderr).toContain("1 blocking finding(s) and 0 advisory(ies) across");
    });
});
